name: Test Backtest System

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Test data manager
      run: |
        python -c "from data_manager import DataManager; print('DataManager imported successfully')"
    
    - name: Test strategy imports
      run: |
        python -c "
        from strategies.sma_strategy import SMAStrategy
        from strategies.rsi_strategy import RSIStrategy
        print('All strategies imported successfully')
        "
    
    - name: Run basic backtest test
      run: |
        # 创建一个简单的测试脚本
        cat > test_backtest.py << 'EOF'
#!/usr/bin/env python3
"""测试回测系统基本功能"""

import sys
import os

# 添加项目根目录到Python路径
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

def test_imports():
    """测试所有模块导入"""
    try:
        from main import MultiStrategyBacktestSystem
        from data_manager import DataManager
        from performance_analyzer import PerformanceAnalyzer
        from report_generator import ReportGenerator
        
        print("✅ 所有模块导入成功")
        
        # 创建实例
        system = MultiStrategyBacktestSystem()
        print("✅ 回测系统实例创建成功")
        
        # 检查支持的策略
        strategies = list(system.strategies.keys())
        print(f"✅ 支持的策略: {strategies}")
        
        return True
        
    except Exception as e:
        print(f"❌ 导入失败: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    if test_imports():
        print("\n✅ 测试通过！")
        sys.exit(0)
    else:
        print("\n❌ 测试失败！")
        sys.exit(1)
EOF
        
        python test_backtest.py
    
    - name: Check file structure
      run: |
        echo "项目结构:"
        find . -type f -name "*.py" | head -20
        echo ""
        echo "requirements.txt 内容:"
        cat requirements.txt
